<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="POU" Id="{c4c8e131-3f59-41d1-b7f8-f21eab12f57a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Nieuwe POU

//Weer een toevoeging]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="1" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>