<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Teltonika" Id="{ce5c4c16-d731-4cac-8a46-0d3c64bd48ea}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Teltonika
VAR
	stRouterParams : st_router_params;
	realconverter : dwtoreal;
	w_SendSMS: WORD;
END_VAR
VAR_OUTPUT
	Get	:	st_router_data;
END_VAR
VAR
	MBRead			: 	FB_MBReadRegs;
	MBWrite			:	FB_MBWriteRegs;
	MBSingleWrite	:	FB_MBWriteSingleReg;
	
	arw_DataBuffer		: 	ARRAY[0..62] OF word;
	st_WriteSMSData		:	STRING(20);

	ar_SMSData			:	ARRAY[0..89] OF WORD;
	ar_ReadSMSData		:	ARRAY[0..89] OF WORD;

	
	ton_GetDataTimer				:	TON := (PT := TIME#1000MS);

	
	ftrig_TransmissionDone	:	F_trig;
	
	ui_MBRetryCount			:	UINT;
	ui_SMSRetryCounter	:	UINT;
		
	ui_ForCounter	:	UINT;
	ui_MessageCounter	:	UINT;
	b_busy: BOOL;
	b_CommError: BOOL;
	udi_errid: UDINT;
	udi_cbread: UDINT;
	
END_VAR


VAR_IN_OUT
	s_Message	:	ARRAY[*] OF STRING(75);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[ton_GetDataTimer(IN:=NOT ton_GetDataTimer.Q);

ReadDataSFC();

get.Events.b_MBCommWarning := ui_MBRetryCount > 5;
IF ui_MBRetryCount > 50 THEN
	get.Events.b_MBCommError := TRUE;
END_IF]]></ST>
    </Implementation>
    <Folder Name="SFC" Id="{f4d5eef4-c143-4170-8575-a31d9721c5b0}" />
    <Action Name="aCheckAlarmMessages" Id="{8bb623ce-e32a-4247-9eea-59e963096791}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[
IF get.e_SMSStatus = eSMSStatus.Idle OR get.e_SMSStatus = eSMSStatus.error THEN
	//skip through message array until non_empty value or the end of the list is found 
	WHILE (s_Message[ui_MessageCounter] = '') AND (ui_MessageCounter < UPPER_BOUND(s_message, 1)) DO
		ui_MessageCounter := ui_MessageCounter + 1;
	END_WHILE
	
	IF (s_Message[ui_MessageCounter] <> '') THEN
		CreateMessage(s_Message[ui_MessageCounter]);	//check for valid message
		get.e_SMSStatus := eSMSStatus.NewMessage;
		s_Message[ui_MessageCounter] := '';
	END_IF
	
	IF ui_MessageCounter >= UPPER_BOUND(s_message, 1) THEN
		ui_MessageCounter := DINT_TO_UINT(LOWER_BOUND(s_message, 1)); 
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aNetworkinfo" Id="{d8e545ad-0207-4319-80fa-b51b970a255b}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[MBRead(
	sIPAddr := stRouterparams.IP_TELTONIKA,
	nTCPPort := stRouterparams.MBPort_TELTONIKA,
	nUnitID := 1,
	nMBAddr := 103,
	nQuantity := 32,//*2,
	cbLength := SIZEOF(arw_DataBuffer),
	pDestAddr := ADR(arw_DataBuffer),
	bExecute := ton_GetDataTimer.Q,
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	tTimeout := stRouterparams.T_MBTimeout
);

ftrig_TransmissionDone(clk := b_busy);

IF ftrig_TransmissionDone.q THEN
	IF NOT b_CommError THEN
		FOR ui_ForCounter := 0 TO 31 DO
			arw_DataBuffer[ui_ForCounter] := be16_TO_HOST(arw_DataBuffer[ui_ForCounter]);
		END_FOR
		
		MEMCPY(ADR(Get.Mobile.NetworkInfo),  ADR(arw_DataBuffer[0]), 32);
		MEMCPY(ADR(Get.Mobile.NetworkType),  ADR(arw_DataBuffer[16]), 32);
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		sfctip := TRUE;
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadActiveSim" Id="{44a57084-24be-4d2d-b636-a258a594fbe8}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[
MBRead(
	sIPAddr := stRouterparams.IP_TELTONIKA,
	nTCPPort := stRouterparams.MBPort_TELTONIKA,
	nUnitID := 1,
	nMBAddr := 205,
	nQuantity := 1,//*2,
	cbLength := SIZEOF(arw_DataBuffer),
	pDestAddr := ADR(arw_DataBuffer),
	bExecute := ton_GetDataTimer.Q,
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	tTimeout := stRouterparams.T_MBTimeout
);

ftrig_TransmissionDone(clk := b_busy);

IF ftrig_TransmissionDone.q THEN
	IF NOT b_CommError THEN
	
		Get.Mobile.ui_ActiveSim := arw_DataBuffer[0];
	
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		sfctip := TRUE;
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadDataUsageSim1" Id="{c47efe6a-5222-482b-8137-7d1c7960cdfe}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[
MBRead(
	sIPAddr := stRouterparams.IP_TELTONIKA,
	nTCPPort := stRouterparams.MBPort_TELTONIKA,
	nUnitID := 1,
	nMBAddr := 193,
	nQuantity := 4,//*2,
	cbLength := SIZEOF(arw_DataBuffer),
	pDestAddr := ADR(arw_DataBuffer),
	bExecute := ton_GetDataTimer.Q,
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	tTimeout := stRouterparams.T_MBTimeout
);

ftrig_TransmissionDone(clk := b_busy);

IF ftrig_TransmissionDone.q THEN
	IF NOT b_CommError THEN
	
		MEMCPY(ADR(Get.Mobile.ui_Sim1DataReceivedMonth)+2, ADR(arw_DataBuffer[0]), 2);
		MEMCPY(ADR(Get.Mobile.ui_Sim1DataReceivedMonth), ADR(arw_DataBuffer[1]), 2);
		
		MEMCPY(ADR(Get.Mobile.ui_Sim1DataSendMonth)+2, ADR(arw_DataBuffer[2]), 2);
		MEMCPY(ADR(Get.Mobile.ui_Sim1DataSendMonth), ADR(arw_DataBuffer[3]), 2);	
	
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		sfctip := TRUE;
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadDataUsageSim2" Id="{a46a9137-6bea-46c4-9399-6f8cdaede783}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[
MBRead(
	sIPAddr := stRouterparams.IP_TELTONIKA,
	nTCPPort := stRouterparams.MBPort_TELTONIKA,
	nUnitID := 1,
	nMBAddr := 308,
	nQuantity := 4,//*2,
	cbLength := SIZEOF(arw_DataBuffer),
	pDestAddr := ADR(arw_DataBuffer),
	bExecute := ton_GetDataTimer.Q,
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	tTimeout := stRouterparams.T_MBTimeout
);

ftrig_TransmissionDone(clk := b_busy);

IF ftrig_TransmissionDone.q THEN
	IF NOT b_CommError THEN
	
		MEMCPY(ADR(Get.Mobile.ui_Sim2DataReceivedMonth)+2, ADR(arw_DataBuffer[0]), 2);
		MEMCPY(ADR(Get.Mobile.ui_Sim2DataReceivedMonth), ADR(arw_DataBuffer[1]), 2);
		
		MEMCPY(ADR(Get.Mobile.ui_Sim2DataSendMonth)+2, ADR(arw_DataBuffer[2]), 2);
		MEMCPY(ADR(Get.Mobile.ui_Sim2DataSendMonth), ADR(arw_DataBuffer[3]), 2);	
	
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		sfctip := TRUE;
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="AReadGeneral" Id="{fc40b227-86e2-44d0-8f40-6ded2a1905ff}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[
MBRead(
	sIPAddr := stRouterparams.IP_TELTONIKA,
	nTCPPort := stRouterparams.MBPort_TELTONIKA,
	nUnitID := 1,
	nMBAddr := 1,
	nQuantity := 6,//*2,
	cbLength := SIZEOF(arw_DataBuffer),
	pDestAddr := ADR(arw_DataBuffer),
	bExecute := ton_GetDataTimer.Q,
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	tTimeout := stRouterparams.T_MBTimeout
);

ftrig_TransmissionDone(clk := b_busy);

IF ftrig_TransmissionDone.q THEN
	IF NOT b_CommError THEN
		
		get.Device.SystemUptime :=	SHL(	WORD_TO_UDINT(	arw_DataBuffer[0]),16)	+	arw_DataBuffer[1];
		MEMCPY(ADR(Get.Mobile.RSSI)+2,  ADR(arw_DataBuffer[2]), 2);
		MEMCPY(ADR(Get.Mobile.RSSI),  ADR(arw_DataBuffer[3]), 2);

		//MEMCPY(ADR(Get.Mobile.NetworkOperator),  ADR(arw_DataBuffer[22]), 32);
		
		get.Device.Temperature	:= 	UDINT_TO_REAL ( SHL(	WORD_TO_UDINT(	arw_DataBuffer[4]),16)	+	arw_DataBuffer[5] )/10;

		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		sfctip := TRUE;
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadGPSData" Id="{6c2c6e09-da82-480e-b334-1a203187c02b}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[

MBRead(
	sIPAddr := stRouterparams.IP_TELTONIKA,
	nTCPPort := stRouterparams.MBPort_TELTONIKA,
	nUnitID := 1,
	nMBAddr := 143,
	nQuantity := 42,//*2,
	cbLength := SIZEOF(arw_DataBuffer),
	pDestAddr := ADR(arw_DataBuffer),
	bExecute := ton_GetDataTimer.Q,
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	tTimeout := stRouterparams.T_MBTimeout
);

ftrig_TransmissionDone(clk := b_busy);

IF ftrig_TransmissionDone.q THEN
	IF NOT b_CommError THEN
		
		realconverter.Registers[2] := arw_DataBuffer[0];
		realconverter.Registers[1] := arw_DataBuffer[1];
		Get.GPS.Latitude  := realconverter.realvalue;
 
		realconverter.Registers[2] := arw_DataBuffer[2];
		realconverter.Registers[1] := arw_DataBuffer[3];
		Get.GPS.Longitude  := realconverter.realvalue;
		
		FOR ui_ForCounter := 4 TO 35 DO
			arw_DataBuffer[ui_ForCounter] := be16_TO_HOST(arw_DataBuffer[ui_ForCounter]);
		END_FOR
				
		MEMCPY(ADR(Get.GPS.FixTime),  ADR(arw_DataBuffer[4]), 32);			//GPS fixtime (text, unix timetamp * 1000)
		
		MEMCPY(ADR(Get.GPS.DateTime), ADR(arw_DataBuffer[20]), 32);			//GPS DateTime (text, YYYY-MM-DD HH:MM:SS)
		
		realconverter.Registers[2] := arw_DataBuffer[36];					//GPS speed
		realconverter.Registers[1] := arw_DataBuffer[37];
		Get.GPS.Speed  := realconverter.realvalue;
		
	
		MEMCPY(ADR(Get.GPS.SatCount)+2, ADR(arw_DataBuffer[38]), 2);			//GPS sattelite count
		MEMCPY(ADR(Get.GPS.SatCount), ADR(arw_DataBuffer[39]), 2);			//GPS sattelite count
		
		realconverter.Registers[2] := arw_DataBuffer[40];
		realconverter.Registers[1] := arw_DataBuffer[41];
		Get.GPS.Accuracy  := realconverter.realvalue;						//GPS accuracy
		
			
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		sfctip := TRUE;
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadSerial" Id="{709e3d7b-e520-4ed8-84a9-db04b277e3ea}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[MBRead(
	sIPAddr := stRouterparams.IP_TELTONIKA,
	nTCPPort := stRouterparams.MBPort_TELTONIKA,
	nUnitID := 1,
	nMBAddr := 39,
	nQuantity := 16,//*2,
	cbLength := SIZEOF(arw_DataBuffer),
	pDestAddr := ADR(arw_DataBuffer),
	bExecute := ton_GetDataTimer.Q,
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	tTimeout := stRouterparams.T_MBTimeout
);

ftrig_TransmissionDone(clk := b_busy);

IF ftrig_TransmissionDone.q THEN
	IF NOT b_CommError THEN
		FOR ui_ForCounter := 0 TO 16 DO
			arw_DataBuffer[ui_ForCounter] := be16_TO_HOST(arw_DataBuffer[ui_ForCounter]);
		END_FOR
		
		//MEMCPY(ADR(Get.Mobile.NetworkOperator),  ADR(arw_DataBuffer[0]), 32);
		MEMCPY(ADR(Get.Device.RouterSerial),  ADR(arw_DataBuffer[0]), 32);
		
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		sfctip := TRUE;
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="aSendSMS" Id="{6390c9e1-ff00-4b14-bfc1-4efb550b3995}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[
IF get.e_SMSStatus = eSMSStatus.SendingMessage THEN
	MBSingleWrite(
		sIPAddr := stRouterparams.IP_TELTONIKA,
		nTCPPort := stRouterparams.MBPort_TELTONIKA,
		nUnitID := 1,
		nMBAddr := 396,
		nValue	:=	1,
		bExecute := ton_GetDataTimer.Q,
		bBusy => b_busy,
		bError => b_CommError,
		nErrId => udi_errid,
		tTimeout := stRouterparams.T_MBTimeout
	);
	
	ftrig_TransmissionDone(clk := b_busy);
	
	IF ftrig_TransmissionDone.q THEN
		IF NOT b_CommError THEN
			get.e_SMSStatus := eSMSSTatus.idle;
			//memcpy(ADR(get.Mobile.st_LatestSMSReceiver), ADR(ar_SMSData[0]), 20);		
			//memcpy(ADR(get.Mobile.st_LatestSMSReceiver), ADR(ar_SMSData[10]), 80);		
			ui_SMSRetryCounter := 0;
			ui_MBRetryCount := 0;
			sfctip := TRUE;
		ELSE
			ui_MBRetryCount := ui_MBRetryCount + 1;
			ui_SMSRetryCounter := ui_SMSRetryCounter + 1;
			IF ui_SMSRetryCounter > 0 THEN
				get.Events.b_SMSNotSendError := TRUE;
				get.e_SMSStatus := eSMSStatus.error;
				sfctip := TRUE;
			END_IF
		END_IF
	END_IF
ELSE
	SFCtip := NOT SFCTip;
END_IF


]]></ST>
      </Implementation>
    </Action>
    <Action Name="aWriteSMSData" Id="{f2cd87f2-3ec6-4b9a-960d-7ee9b04df6de}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[
MBWrite(
	sIPAddr := stRouterparams.IP_TELTONIKA,
	nTCPPort := stRouterparams.MBPort_TELTONIKA,
	nUnitID := 1,
	nMBAddr := 397,
	nQuantity := 90,
	cbLength := SIZEOF(ar_SMSData),
	pSrcAddr	:=	ADR(ar_SMSData),
	bExecute := ton_GetDataTimer.Q,
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	tTimeout := stRouterparams.T_MBTimeout
);

ftrig_TransmissionDone(clk := b_busy);

IF ftrig_TransmissionDone.q THEN
	IF NOT b_CommError THEN
		get.e_SMSStatus := eSMSStatus.SendingMessage;
		ui_SMSRetryCounter := 0;
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_SMSRetryCounter := ui_SMSRetryCounter +1;
		ui_MBRetryCount := ui_MBRetryCount + 1;
		IF ui_SMSRetryCounter > 3 THEN
			get.Events.b_SMSNotSendError := TRUE;
			get.e_SMSStatus := eSMSStatus.error;
			sfctip := TRUE;
		END_IF
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Method Name="CreateMessage" Id="{313919e7-6b12-4358-9d52-916d3392c894}">
      <Declaration><![CDATA[METHOD CreateMessage : BOOL
VAR_INPUT
//	TelNumber	:	ULINT;
	s_Message		:	STRING(80);
END_VAR

VAR
	s_InternalMessage 	: 	STRING(160);
	s_LAT				:	STRING(8);
	s_LONG				:	STRING(9);
	ui_counter			:	UINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
memcpy(ADR(ar_SMSData[0]), ADR(get.Mobile.s_EmergencySMSNumber), 20);

s_LAT := REAL_TO_STRING(get.GPS.Latitude);
s_LONG := REAL_TO_STRING(get.GPS.Longitude);

s_InternalMessage := 'ePU10 LFP Battery System Alarm';
s_InternalMessage := concat(s_InternalMessage, '$n');
s_InternalMessage := concat(s_InternalMessage, 'ID: ');
s_InternalMessage := concat(s_InternalMessage, get.mobile.s_EmergencySMSDevName);
s_InternalMessage := concat(s_InternalMessage, '$n');
s_InternalMessage := concat(s_InternalMessage, 'LAT: ');
s_InternalMessage := concat(s_InternalMessage, s_LAT);
s_InternalMessage := concat(s_InternalMessage, '$n');
s_InternalMessage := concat(s_InternalMessage, 'LON: ');
s_InternalMessage := concat(s_InternalMessage, s_LONG);
s_InternalMessage := concat(s_InternalMessage, '$n');
s_InternalMessage := concat(s_InternalMessage,s_Message);

memcpy(ADR(ar_SMSData[10]), ADR(s_InternalMessage[0]), 160);

FOR ui_counter := 0 TO 89 DO
	ar_SMSData[ui_counter] := host_to_be16(ar_SMSData[ui_counter]);
END_FOR

CreateMessage := TRUE;

 ]]></ST>
      </Implementation>
    </Method>
    <Method Name="EMStop" Id="{6ba89e65-66e3-4e9c-adf4-3239c5d5f77d}">
      <Declaration><![CDATA[METHOD EMStop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//nothing to do here
EMSTOP := TRUE;]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetDiagnostics" Id="{40b6fdc8-4d98-479c-b936-17011da3130d}">
      <Declaration><![CDATA[METHOD GetDiagnostics : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Action Name="ReadDataSFC" Id="{4a4da098-fd72-47ce-861d-90616dad5bf0}" FolderPath="SFC\">
      <Implementation>
        <SFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="SFCImplementationObject">
                <o n="Root" t="SFCSegment">
                  <o n="ElementList" t="SFCElementList">
                    <l2 n="InnerList">
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"init"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">3L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">4L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">5L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">6L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">7L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">8L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">9L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">10L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">11L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">12L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">13L</v>
                            <v n="IdParent">2L</v>
                          </o>
                        </l2>
                        <v n="Id">2L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"init__to__ReadGeneral"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"True"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">26L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">27L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">28L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">29L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">30L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">31L</v>
                            <v n="IdParent">25L</v>
                          </o>
                        </l2>
                        <v n="Id">25L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"ReadGeneral"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">186L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">187L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">188L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">189L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">190L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">191L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">192L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">193L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"AReadGeneral"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">194L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">195L</v>
                            <v n="IdParent">185L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">196L</v>
                            <v n="IdParent">185L</v>
                          </o>
                        </l2>
                        <v n="Id">185L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"ReadGeneral__to__ReadSerial"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"false"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">198L</v>
                            <v n="IdParent">197L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">199L</v>
                            <v n="IdParent">197L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">200L</v>
                            <v n="IdParent">197L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">201L</v>
                            <v n="IdParent">197L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">202L</v>
                            <v n="IdParent">197L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">203L</v>
                            <v n="IdParent">197L</v>
                          </o>
                        </l2>
                        <v n="Id">197L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"ReadSerial"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">205L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">206L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">207L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">208L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">209L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">210L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">211L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">212L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadSerial"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">213L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">214L</v>
                            <v n="IdParent">204L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"sfctipreset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">215L</v>
                            <v n="IdParent">204L</v>
                          </o>
                        </l2>
                        <v n="Id">204L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"ReadSerial__to__ReadGPSData"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"false"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">217L</v>
                            <v n="IdParent">216L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">218L</v>
                            <v n="IdParent">216L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">219L</v>
                            <v n="IdParent">216L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">220L</v>
                            <v n="IdParent">216L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">221L</v>
                            <v n="IdParent">216L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">222L</v>
                            <v n="IdParent">216L</v>
                          </o>
                        </l2>
                        <v n="Id">216L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"ReadGPSData"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">33L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">34L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">35L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">36L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">37L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">38L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">39L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">40L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadGPSData"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">41L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">42L</v>
                            <v n="IdParent">32L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"sfctipreset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">43L</v>
                            <v n="IdParent">32L</v>
                          </o>
                        </l2>
                        <v n="Id">32L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"ReadGPSData__to__Sim1Data"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">49L</v>
                            <v n="IdParent">48L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">50L</v>
                            <v n="IdParent">48L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">51L</v>
                            <v n="IdParent">48L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">52L</v>
                            <v n="IdParent">48L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">53L</v>
                            <v n="IdParent">48L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">54L</v>
                            <v n="IdParent">48L</v>
                          </o>
                        </l2>
                        <v n="Id">48L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Sim1Data"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">91L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">92L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">93L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">94L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">95L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">96L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">97L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">98L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadDataUsageSim1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">99L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">100L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">101L</v>
                            <v n="IdParent">90L</v>
                          </o>
                        </l2>
                        <v n="Id">90L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Sim1Data__to__Sim2Data"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"false"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">103L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">104L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">105L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">106L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">107L</v>
                            <v n="IdParent">102L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">108L</v>
                            <v n="IdParent">102L</v>
                          </o>
                        </l2>
                        <v n="Id">102L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Sim2Data"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">110L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">111L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">112L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">113L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">114L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">115L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">116L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">117L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadDataUsageSim2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">118L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">119L</v>
                            <v n="IdParent">109L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">120L</v>
                            <v n="IdParent">109L</v>
                          </o>
                        </l2>
                        <v n="Id">109L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Sim2Data__to__Networkinfo"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"false"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">122L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">123L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">124L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">125L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">126L</v>
                            <v n="IdParent">121L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">127L</v>
                            <v n="IdParent">121L</v>
                          </o>
                        </l2>
                        <v n="Id">121L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Networkinfo"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">224L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">225L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">226L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">227L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">228L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">229L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">230L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">231L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aNetworkinfo"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">232L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">233L</v>
                            <v n="IdParent">223L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">234L</v>
                            <v n="IdParent">223L</v>
                          </o>
                        </l2>
                        <v n="Id">223L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Networkinfo__to__ActiveSim"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"false"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">236L</v>
                            <v n="IdParent">235L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">237L</v>
                            <v n="IdParent">235L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">238L</v>
                            <v n="IdParent">235L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">239L</v>
                            <v n="IdParent">235L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">240L</v>
                            <v n="IdParent">235L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">241L</v>
                            <v n="IdParent">235L</v>
                          </o>
                        </l2>
                        <v n="Id">235L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"ActiveSim"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">148L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">149L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">150L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">151L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">152L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">153L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">154L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">155L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadActiveSim"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">156L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">157L</v>
                            <v n="IdParent">147L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">158L</v>
                            <v n="IdParent">147L</v>
                          </o>
                        </l2>
                        <v n="Id">147L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"ActiveSim__to__CheckAlarmMessages"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"false"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">160L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">161L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">162L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">163L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">164L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">165L</v>
                            <v n="IdParent">159L</v>
                          </o>
                        </l2>
                        <v n="Id">159L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"CheckAlarmMessages"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">805L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">806L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">807L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">808L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">809L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">810L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">811L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">812L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aCheckAlarmMessages"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">813L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">814L</v>
                            <v n="IdParent">804L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">815L</v>
                            <v n="IdParent">804L</v>
                          </o>
                        </l2>
                        <v n="Id">804L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCBranch">
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCSegment">
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList">
                                  <o t="SFCTransition">
                                    <v n="VariableName">"Branch0__CheckAlarmMessages__to__WriteSMS"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"get.e_SMSStatus = eSMSStatus.NewMessage"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">729L</v>
                                        <v n="IdParent">728L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">730L</v>
                                        <v n="IdParent">728L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">731L</v>
                                        <v n="IdParent">728L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">732L</v>
                                        <v n="IdParent">728L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">733L</v>
                                        <v n="IdParent">728L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">734L</v>
                                        <v n="IdParent">728L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">728L</v>
                                    <v n="IdParent">708L</v>
                                  </o>
                                  <o t="SFCStep">
                                    <n n="EmbeddedMainAction" />
                                    <n n="EmbeddedEntryAction" />
                                    <n n="EmbeddedExitAction" />
                                    <l2 n="EmbeddedMainActionProperties" />
                                    <l2 n="EmbeddedEntryActionProperties" />
                                    <l2 n="EmbeddedExitActionProperties" />
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" />
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"WriteSMS"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">854L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">855L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">856L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">857L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">858L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">859L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">860L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">861L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"aWriteSMSData"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">862L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">863L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"SFCTipReset"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">864L</v>
                                        <v n="IdParent">853L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">853L</v>
                                    <v n="IdParent">708L</v>
                                  </o>
                                  <o t="SFCTransition">
                                    <v n="VariableName">"WriteSMS__to__SendSMS"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"false"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">847L</v>
                                        <v n="IdParent">846L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">848L</v>
                                        <v n="IdParent">846L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">849L</v>
                                        <v n="IdParent">846L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">850L</v>
                                        <v n="IdParent">846L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">851L</v>
                                        <v n="IdParent">846L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">852L</v>
                                        <v n="IdParent">846L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">846L</v>
                                    <v n="IdParent">708L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">709L</v>
                                  <v n="IdParent">708L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">710L</v>
                                  <v n="IdParent">708L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">711L</v>
                                  <v n="IdParent">708L</v>
                                </o>
                              </l2>
                              <v n="Id">708L</v>
                              <v n="IdParent">703L</v>
                            </o>
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList">
                                  <o t="SFCTransition">
                                    <v n="VariableName">"Branch1__CheckAlarmMessages__to__empty"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"get.e_SMSStatus &lt;&gt; eSMSStatus.NewMessage"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">748L</v>
                                        <v n="IdParent">747L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">749L</v>
                                        <v n="IdParent">747L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">750L</v>
                                        <v n="IdParent">747L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">751L</v>
                                        <v n="IdParent">747L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">752L</v>
                                        <v n="IdParent">747L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">753L</v>
                                        <v n="IdParent">747L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">747L</v>
                                    <v n="IdParent">712L</v>
                                  </o>
                                  <o t="SFCStep">
                                    <n n="EmbeddedMainAction" />
                                    <n n="EmbeddedEntryAction" />
                                    <n n="EmbeddedExitAction" />
                                    <l2 n="EmbeddedMainActionProperties" />
                                    <l2 n="EmbeddedEntryActionProperties" />
                                    <l2 n="EmbeddedExitActionProperties" />
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" />
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"empty"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">717L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">718L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">719L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">720L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">721L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">722L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">723L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">724L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">725L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">726L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">727L</v>
                                        <v n="IdParent">716L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">716L</v>
                                    <v n="IdParent">712L</v>
                                  </o>
                                  <o t="SFCTransition">
                                    <v n="VariableName">"empty__to__SendSMS"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"True"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">786L</v>
                                        <v n="IdParent">785L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">787L</v>
                                        <v n="IdParent">785L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">788L</v>
                                        <v n="IdParent">785L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">789L</v>
                                        <v n="IdParent">785L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">790L</v>
                                        <v n="IdParent">785L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">791L</v>
                                        <v n="IdParent">785L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">785L</v>
                                    <v n="IdParent">712L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">713L</v>
                                  <v n="IdParent">712L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">714L</v>
                                  <v n="IdParent">712L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">715L</v>
                                  <v n="IdParent">712L</v>
                                </o>
                              </l2>
                              <v n="Id">712L</v>
                              <v n="IdParent">703L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Branch0_ReadDataSFC"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">704L</v>
                            <v n="IdParent">703L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">705L</v>
                            <v n="IdParent">703L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">706L</v>
                            <v n="IdParent">703L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">707L</v>
                            <v n="IdParent">703L</v>
                          </o>
                        </l2>
                        <v n="Id">703L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SendSMS"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">654L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">655L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">656L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">657L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">658L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">659L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">660L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">661L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aSendSMS"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">662L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">663L</v>
                            <v n="IdParent">653L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">664L</v>
                            <v n="IdParent">653L</v>
                          </o>
                        </l2>
                        <v n="Id">653L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"SendSMS__to__Init"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"false"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">647L</v>
                            <v n="IdParent">646L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">648L</v>
                            <v n="IdParent">646L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">649L</v>
                            <v n="IdParent">646L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">650L</v>
                            <v n="IdParent">646L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">651L</v>
                            <v n="IdParent">646L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">652L</v>
                            <v n="IdParent">646L</v>
                          </o>
                        </l2>
                        <v n="Id">646L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCJump">
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">68L</v>
                            <v n="IdParent">67L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">69L</v>
                            <v n="IdParent">67L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">70L</v>
                            <v n="IdParent">67L</v>
                          </o>
                        </l2>
                        <v n="Id">67L</v>
                        <v n="IdParent">1L</v>
                      </o>
                    </l2>
                  </o>
                  <l2 n="Attributes" cet="SFCAttribute">
                    <o>
                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">865L</v>
                      <v n="IdParent">1L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">866L</v>
                      <v n="IdParent">1L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                      <o n="Value" t="BoolValue">
                        <v n="Value">"FALSE"</v>
                        <v n="DefaultValue">"FALSE"</v>
                      </o>
                      <v n="Id">867L</v>
                      <v n="IdParent">1L</v>
                    </o>
                  </l2>
                  <v n="Id">1L</v>
                  <v n="IdParent">-1L</v>
                </o>
                <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                  <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Identifier">"Specific"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Element type specific properties"</v>
                  </o>
                  <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Identifier">"Actions"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Action definitions"</v>
                  </o>
                  <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Identifier">"Common"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Common properties"</v>
                  </o>
                  <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Identifier">"Times"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Time definitions"</v>
                  </o>
                </d2>
                <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                  <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">true</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <v n="Identifier">"Exclude"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Exclude this element from build"</v>
                  </o>
                  <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                    <v n="Identifier">"Parallel"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the branch to parallel mode"</v>
                  </o>
                  <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <v n="Identifier">"Name"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Name of the element"</v>
                  </o>
                  <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                    <v n="Identifier">"Duplication"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                  </o>
                  <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                    <v n="Identifier">"InitStep"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the step as the initial step"</v>
                  </o>
                  <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                    <v n="Identifier">"MainAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is active"</v>
                  </o>
                  <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">true</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <v n="Identifier">"Comment"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Comment of the element"</v>
                  </o>
                  <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                    <v n="Identifier">"Monitoring"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Indicates transition monitoring setting."</v>
                  </o>
                  <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                    <v n="Identifier">"ExitAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                  </o>
                  <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                    <v n="Identifier">"EntryAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is activated"</v>
                  </o>
                  <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                    <v n="Identifier">"MaxTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the maximal active time for the step"</v>
                  </o>
                  <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                    <v n="Identifier">"Symbol"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Symbol configuration setting of the element"</v>
                  </o>
                  <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                    <v n="Identifier">"MinTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the minimal active time for the step"</v>
                  </o>
                  <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                    <v n="Identifier">"Qualifier"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Qualifier of the action association"</v>
                  </o>
                </d2>
                <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                  <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                  <o>
                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Variable"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"Variable"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Call"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Call"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                  <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                  <o>
                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"Unspecified"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"Unspecified"</v>
                      </o>
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Read"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Read"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Write"</v>
                        <v n="Value">3L</v>
                        <v n="Key">"Write"</v>
                      </o>
                      <o>
                        <v n="Identifier">"ReadWrite"</v>
                        <v n="Value">4L</v>
                        <v n="Key">"ReadWrite"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                </d2>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
              <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
              <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
              <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
              <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
              <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
              <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
              <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
              <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
              <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
              <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
              <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
              <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
              <Type n="String">System.String</Type>
              <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
            </TypeList>
          </XmlArchive>
        </SFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCProperty">
              <n n="SFCErrorAnalyzation" />
              <n n="SFCErrorAnalyzationTable" />
              <v n="Title">"IecSfc"</v>
              <v n="Company">"System"</v>
              <v n="Version">"3.4.2.0"</v>
              <v n="Namespace">""</v>
              <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
                <v>EnableLimit</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Init</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>Reset</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>QuitError</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Pause</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Error</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Trans</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorPOU</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Tip</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>TipMode</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzation</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzationTable</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
              </d2>
              <v n="CalcActiveTransOnly">false</v>
              <v n="UseDefaults">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
            <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
            <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Method Name="Reset" Id="{bd7c570d-38bf-480e-a9c9-2d2f0b0af6b7}">
      <Declaration><![CDATA[METHOD Reset : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
get.Events.b_MBCommError := FALSE;
get.Events.b_MBCommError := FALSE;
get.Events.b_SMSNotSendError := FALSE;
get.e_SMSStatus := eSMSStatus.Idle;

Reset := TRUE;]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetDevName" Id="{0b75bd53-ab4d-436d-b710-af600db034db}">
      <Declaration><![CDATA[METHOD SetDevName : BOOL
VAR_INPUT
	s_DevName	:	String(12);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF s_DevName = '' THEN
	get.Mobile.s_EmergencySMSDevName := 'serial'; //<-- stParams.serial number
ELSE
	get.Mobile.s_EmergencySMSDevName :=	s_DevName;
END_IF

SetDevName := True;]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetSMSNumber" Id="{b87a798f-bceb-4992-bb50-ae879adcce42}">
      <Declaration><![CDATA[METHOD SetSMSNumber : BOOL
VAR_INPUT
	s_SMSNumber	:	STRING(20);
END_VAR
VAR 
	for_counter	:	UINT :=0;
	InternalString	:	STRING(20);
	intermediateValue	:	UINT;
	
	temp	:	string(10);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[
SetSMSNumber := TRUE;

//check minimum length
IF INT_TO_UINT(len(s_SMSNumber)) < stRouterParams.MinimumPhoneNumberLength THEN
	SetSMSNumber := FALSE;
ELSE
	InternalString := s_SMSNumber;
	
	//replace leading + with 00
	IF left(InternalString,1) = '+' THEN
		InternalString := Replace(InternalString, '00', 1, 1);
	END_IF
	
	//check for non_numeric characters
	FOR for_counter := 1 TO INT_TO_UINT(len(InternalString)) DO
		intermediateValue := f_toASC(mid(InternalString, 1, UINT_TO_INT(for_counter)));
		IF (intermediateValue < 48 OR intermediateValue > 57) THEN
			SetSMSNumber := FALSE;
		END_IF
	END_FOR
END_IF

//only if all checks succeed, the number is written to the struct.
IF SetSMSNumber THEN
	get.Mobile.s_EmergencySMSNumber := InternalString;
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Action Name="SFCTipReset" Id="{67752440-1bb6-4e7c-a33c-97f3b09a1c60}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[SFCTip := FALSE;]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="FB_Teltonika">
      <LineId Id="23" Count="0" />
      <LineId Id="326" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="410" Count="0" />
      <LineId Id="200" Count="0" />
      <LineId Id="413" Count="0" />
      <LineId Id="411" Count="1" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aCheckAlarmMessages">
      <LineId Id="33" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="21" Count="1" />
      <LineId Id="24" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="28" Count="2" />
      <LineId Id="26" Count="1" />
      <LineId Id="11" Count="0" />
      <LineId Id="31" Count="1" />
      <LineId Id="34" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aNetworkinfo">
      <LineId Id="31" Count="19" />
      <LineId Id="73" Count="2" />
      <LineId Id="72" Count="0" />
      <LineId Id="51" Count="7" />
      <LineId Id="30" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aReadActiveSim">
      <LineId Id="2" Count="22" />
      <LineId Id="29" Count="7" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aReadDataUsageSim1">
      <LineId Id="3" Count="21" />
      <LineId Id="59" Count="2" />
      <LineId Id="75" Count="0" />
      <LineId Id="74" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="67" Count="6" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aReadDataUsageSim2">
      <LineId Id="3" Count="21" />
      <LineId Id="59" Count="2" />
      <LineId Id="75" Count="0" />
      <LineId Id="74" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="67" Count="6" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.AReadGeneral">
      <LineId Id="2" Count="0" />
      <LineId Id="4" Count="20" />
      <LineId Id="79" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="82" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="84" Count="1" />
      <LineId Id="74" Count="0" />
      <LineId Id="66" Count="7" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aReadGPSData">
      <LineId Id="100" Count="1" />
      <LineId Id="2" Count="18" />
      <LineId Id="22" Count="1" />
      <LineId Id="104" Count="0" />
      <LineId Id="123" Count="0" />
      <LineId Id="141" Count="1" />
      <LineId Id="153" Count="1" />
      <LineId Id="152" Count="0" />
      <LineId Id="135" Count="0" />
      <LineId Id="202" Count="1" />
      <LineId Id="201" Count="0" />
      <LineId Id="204" Count="2" />
      <LineId Id="136" Count="0" />
      <LineId Id="190" Count="0" />
      <LineId Id="193" Count="1" />
      <LineId Id="191" Count="1" />
      <LineId Id="196" Count="0" />
      <LineId Id="140" Count="0" />
      <LineId Id="195" Count="0" />
      <LineId Id="200" Count="0" />
      <LineId Id="198" Count="1" />
      <LineId Id="197" Count="0" />
      <LineId Id="103" Count="0" />
      <LineId Id="102" Count="0" />
      <LineId Id="84" Count="4" />
      <LineId Id="98" Count="1" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aReadSerial">
      <LineId Id="4" Count="19" />
      <LineId Id="38" Count="1" />
      <LineId Id="37" Count="0" />
      <LineId Id="40" Count="1" />
      <LineId Id="26" Count="0" />
      <LineId Id="30" Count="6" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aSendSMS">
      <LineId Id="40" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="49" Count="16" />
      <LineId Id="68" Count="1" />
      <LineId Id="80" Count="0" />
      <LineId Id="83" Count="0" />
      <LineId Id="73" Count="3" />
      <LineId Id="82" Count="0" />
      <LineId Id="84" Count="0" />
      <LineId Id="86" Count="1" />
      <LineId Id="77" Count="0" />
      <LineId Id="85" Count="0" />
      <LineId Id="78" Count="0" />
      <LineId Id="41" Count="0" />
      <LineId Id="43" Count="1" />
      <LineId Id="42" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.aWriteSMSData">
      <LineId Id="2" Count="19" />
      <LineId Id="23" Count="4" />
      <LineId Id="32" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="34" Count="1" />
      <LineId Id="30" Count="1" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.CreateMessage">
      <LineId Id="51" Count="1" />
      <LineId Id="36" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="37" Count="1" />
      <LineId Id="18" Count="0" />
      <LineId Id="23" Count="1" />
      <LineId Id="26" Count="0" />
      <LineId Id="57" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="39" Count="1" />
      <LineId Id="31" Count="0" />
      <LineId Id="41" Count="2" />
      <LineId Id="5" Count="0" />
      <LineId Id="48" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="49" Count="1" />
      <LineId Id="56" Count="0" />
      <LineId Id="55" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="44" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.EMStop">
      <LineId Id="6" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.GetDiagnostics">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.Reset">
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="1" />
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.SetDevName">
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="9" Count="1" />
      <LineId Id="8" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="11" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.SetSMSNumber">
      <LineId Id="7" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="22" Count="1" />
      <LineId Id="27" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="19" Count="1" />
      <LineId Id="24" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="29" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="33" Count="1" />
      <LineId Id="18" Count="0" />
    </LineIds>
    <LineIds Name="FB_Teltonika.SFCTipReset">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>