<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_HeatPumpSystem" Id="{fd3ced53-38d6-4a15-8e68-1fb19bd16ace}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HeatPumpSystem
VAR_INPUT
END_VAR
VAR
	PrimaryHeatpump: FB_Heatpump;
	HeatPumpInitTimeout: TON := (PT := TIME#3S0MS);
END_VAR

VAR_IN_OUT
	b_EnablePower 	: BOOL;
	//r_Setpoint 		: REAL;

//	Faults: ST_CoolingSystemEvents; 
//	HPSSet: ST_CoolingStackSet;
END_VAR

VAR_OUTPUT
	Get : ST_HeatpumpSystemGet;
END_VAR

VAR
	SecondHPPowerOnDelay: 	TON := (PT := TIME#250MS);
	IO	:	FB_HeatpumpSystem_IO;
	MBcommBusy	:	BOOL;
	CommFreeForID	:	BYTE	:= 0;
	CommFreeTimeout	:	TON 	:= (PT := TIME#5s0ms);
	SecondaryHeatPump: FB_Heatpump;
END_VAR]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList">
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCActionAssociation">
                          <o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"aContinuousActions"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">651L</v>
                                <v n="IdParent">650L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">652L</v>
                                <v n="IdParent">650L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">653L</v>
                                <v n="IdParent">650L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                <o n="Value" t="EnumValue">
                                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                  <n n="BaseType" />
                                  <v n="Value">"0"</v>
                                  <v n="DefaultValue">"0"</v>
                                </o>
                                <v n="Id">654L</v>
                                <v n="IdParent">650L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"S"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">655L</v>
                                <v n="IdParent">650L</v>
                              </o>
                            </l2>
                            <v n="Id">650L</v>
                            <v n="IdParent">33L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"OFF"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">34L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">35L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">36L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">37L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">38L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">39L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">40L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">41L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">42L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">43L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"SFCTipReset"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">44L</v>
                          <v n="IdParent">33L</v>
                        </o>
                      </l2>
                      <v n="Id">33L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"OFF__to__InitHP1"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"b_EnablePower"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">46L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">47L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">48L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">49L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">50L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">51L</v>
                          <v n="IdParent">45L</v>
                        </o>
                      </l2>
                      <v n="Id">45L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCMacro">
                      <o n="Segment" t="SFCSegment">
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList">
                            <o t="SFCStep">
                              <n n="EmbeddedMainAction" />
                              <n n="EmbeddedEntryAction" />
                              <n n="EmbeddedExitAction" />
                              <l2 n="EmbeddedMainActionProperties" />
                              <l2 n="EmbeddedEntryActionProperties" />
                              <l2 n="EmbeddedExitActionProperties" />
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList" />
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"InitHP1"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">524L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">525L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">526L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">527L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">528L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">529L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">530L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">531L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"aInitHP1"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">532L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">533L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"SFCTipReset"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">534L</v>
                                  <v n="IdParent">523L</v>
                                </o>
                              </l2>
                              <v n="Id">523L</v>
                              <v n="IdParent">510L</v>
                            </o>
                            <o t="SFCTransition">
                              <v n="VariableName">"InitHP1__to__Step2"</v>
                              <n n="EmbeddedTransition" />
                              <l2 n="EmbeddedTransitionProperties" />
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"False"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">594L</v>
                                  <v n="IdParent">593L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">595L</v>
                                  <v n="IdParent">593L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">596L</v>
                                  <v n="IdParent">593L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">597L</v>
                                  <v n="IdParent">593L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">598L</v>
                                  <v n="IdParent">593L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">599L</v>
                                  <v n="IdParent">593L</v>
                                </o>
                              </l2>
                              <v n="Id">593L</v>
                              <v n="IdParent">510L</v>
                            </o>
                            <o t="SFCStep">
                              <n n="EmbeddedMainAction" />
                              <n n="EmbeddedEntryAction" />
                              <n n="EmbeddedExitAction" />
                              <l2 n="EmbeddedMainActionProperties" />
                              <l2 n="EmbeddedEntryActionProperties" />
                              <l2 n="EmbeddedExitActionProperties" />
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList" />
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Step2"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">601L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">602L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">603L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">604L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">605L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">606L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">607L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">608L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">609L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">610L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">611L</v>
                                  <v n="IdParent">600L</v>
                                </o>
                              </l2>
                              <v n="Id">600L</v>
                              <v n="IdParent">510L</v>
                            </o>
                            <o t="SFCBranch">
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList" cet="SFCSegment">
                                  <o>
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList" cet="SFCTransition">
                                        <o>
                                          <v n="VariableName">"Branch0__Step2__to__InitDone"</v>
                                          <n n="EmbeddedTransition" />
                                          <l2 n="EmbeddedTransitionProperties" />
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"not CoolingSystemParams.DoubleHeatpump"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">517L</v>
                                              <v n="IdParent">516L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">518L</v>
                                              <v n="IdParent">516L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">519L</v>
                                              <v n="IdParent">516L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">520L</v>
                                              <v n="IdParent">516L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">521L</v>
                                              <v n="IdParent">516L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">522L</v>
                                              <v n="IdParent">516L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">516L</v>
                                          <v n="IdParent">559L</v>
                                        </o>
                                      </l2>
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">560L</v>
                                        <v n="IdParent">559L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">561L</v>
                                        <v n="IdParent">559L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">562L</v>
                                        <v n="IdParent">559L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">559L</v>
                                    <v n="IdParent">554L</v>
                                  </o>
                                  <o>
                                    <o n="ElementList" t="SFCElementList">
                                      <l2 n="InnerList">
                                        <o t="SFCTransition">
                                          <v n="VariableName">"Branch1__Step2__to__InitHP2"</v>
                                          <n n="EmbeddedTransition" />
                                          <l2 n="EmbeddedTransitionProperties" />
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"CoolingSystemParams.DoubleHeatpump"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">568L</v>
                                              <v n="IdParent">567L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">569L</v>
                                              <v n="IdParent">567L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">570L</v>
                                              <v n="IdParent">567L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">571L</v>
                                              <v n="IdParent">567L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">572L</v>
                                              <v n="IdParent">567L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">573L</v>
                                              <v n="IdParent">567L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">567L</v>
                                          <v n="IdParent">563L</v>
                                        </o>
                                        <o t="SFCStep">
                                          <n n="EmbeddedMainAction" />
                                          <n n="EmbeddedEntryAction" />
                                          <n n="EmbeddedExitAction" />
                                          <l2 n="EmbeddedMainActionProperties" />
                                          <l2 n="EmbeddedEntryActionProperties" />
                                          <l2 n="EmbeddedExitActionProperties" />
                                          <o n="ElementList" t="SFCElementList">
                                            <l2 n="InnerList" />
                                          </o>
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"InitHP2"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">575L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">576L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">577L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">578L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">579L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">580L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">581L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">582L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"aInitHP2"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">583L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">584L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"SFCTipReset"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">585L</v>
                                              <v n="IdParent">574L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">574L</v>
                                          <v n="IdParent">563L</v>
                                        </o>
                                        <o t="SFCTransition">
                                          <v n="VariableName">"InitHP2__to__InitDone"</v>
                                          <n n="EmbeddedTransition" />
                                          <l2 n="EmbeddedTransitionProperties" />
                                          <l2 n="Attributes" cet="SFCAttribute">
                                            <o>
                                              <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">"false"</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">587L</v>
                                              <v n="IdParent">586L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                              <o n="Value" t="StringValue">
                                                <v n="Value">""</v>
                                                <v n="DefaultValue">""</v>
                                              </o>
                                              <v n="Id">588L</v>
                                              <v n="IdParent">586L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">589L</v>
                                              <v n="IdParent">586L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">590L</v>
                                              <v n="IdParent">586L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                              <o n="Value" t="BoolValue">
                                                <v n="Value">"FALSE"</v>
                                                <v n="DefaultValue">"FALSE"</v>
                                              </o>
                                              <v n="Id">591L</v>
                                              <v n="IdParent">586L</v>
                                            </o>
                                            <o>
                                              <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                              <o n="Value" t="EnumValue">
                                                <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                                <n n="BaseType" />
                                                <v n="Value">"0"</v>
                                                <v n="DefaultValue">"0"</v>
                                              </o>
                                              <v n="Id">592L</v>
                                              <v n="IdParent">586L</v>
                                            </o>
                                          </l2>
                                          <v n="Id">586L</v>
                                          <v n="IdParent">563L</v>
                                        </o>
                                      </l2>
                                    </o>
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">564L</v>
                                        <v n="IdParent">563L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">565L</v>
                                        <v n="IdParent">563L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">566L</v>
                                        <v n="IdParent">563L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">563L</v>
                                    <v n="IdParent">554L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"Branch0"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">555L</v>
                                  <v n="IdParent">554L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">556L</v>
                                  <v n="IdParent">554L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">557L</v>
                                  <v n="IdParent">554L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">558L</v>
                                  <v n="IdParent">554L</v>
                                </o>
                              </l2>
                              <v n="Id">554L</v>
                              <v n="IdParent">510L</v>
                            </o>
                            <o t="SFCStep">
                              <n n="EmbeddedMainAction" />
                              <n n="EmbeddedEntryAction" />
                              <n n="EmbeddedExitAction" />
                              <l2 n="EmbeddedMainActionProperties" />
                              <l2 n="EmbeddedEntryActionProperties" />
                              <l2 n="EmbeddedExitActionProperties" />
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList" />
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"InitDone"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">613L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">614L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">615L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">616L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">617L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">618L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">619L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">620L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"aInitDone"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">621L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">622L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"SFCTipReset"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">623L</v>
                                  <v n="IdParent">612L</v>
                                </o>
                              </l2>
                              <v n="Id">612L</v>
                              <v n="IdParent">510L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">656L</v>
                            <v n="IdParent">510L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">657L</v>
                            <v n="IdParent">510L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">658L</v>
                            <v n="IdParent">510L</v>
                          </o>
                        </l2>
                        <v n="Id">510L</v>
                        <v n="IdParent">506L</v>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"InitHeatpumps"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">507L</v>
                          <v n="IdParent">506L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">508L</v>
                          <v n="IdParent">506L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">509L</v>
                          <v n="IdParent">506L</v>
                        </o>
                      </l2>
                      <v n="Id">506L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"InitDone__to__HeatPumpControl"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Get.HeatPumpStatus = eHeatPumpState.Standby"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">105L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">106L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">107L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">108L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">109L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">110L</v>
                          <v n="IdParent">104L</v>
                        </o>
                      </l2>
                      <v n="Id">104L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"HeatPumpControl"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">213L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">214L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">215L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">216L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">217L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">218L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">219L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">220L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"aHeatPumpControl"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">221L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">222L</v>
                          <v n="IdParent">212L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"SFCTipReset"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">223L</v>
                          <v n="IdParent">212L</v>
                        </o>
                      </l2>
                      <v n="Id">212L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"HeatPumpControl__to__HeatPumpShutdown"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"b_EnablePower = FALSE"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">225L</v>
                          <v n="IdParent">224L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">226L</v>
                          <v n="IdParent">224L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">227L</v>
                          <v n="IdParent">224L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">228L</v>
                          <v n="IdParent">224L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">229L</v>
                          <v n="IdParent">224L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">230L</v>
                          <v n="IdParent">224L</v>
                        </o>
                      </l2>
                      <v n="Id">224L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"HeatPumpShutdown"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">251L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">252L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">253L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">254L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">255L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">256L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">257L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">258L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"aHeatPumpShutdown"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">259L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">260L</v>
                          <v n="IdParent">250L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"SFCTipReset"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">261L</v>
                          <v n="IdParent">250L</v>
                        </o>
                      </l2>
                      <v n="Id">250L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"HeatPumpShutdown__to__OFF"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"True"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">274L</v>
                          <v n="IdParent">273L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">275L</v>
                          <v n="IdParent">273L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">276L</v>
                          <v n="IdParent">273L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">277L</v>
                          <v n="IdParent">273L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">278L</v>
                          <v n="IdParent">273L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">279L</v>
                          <v n="IdParent">273L</v>
                        </o>
                      </l2>
                      <v n="Id">273L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCJump">
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"OFF"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">270L</v>
                          <v n="IdParent">269L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">271L</v>
                          <v n="IdParent">269L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">272L</v>
                          <v n="IdParent">269L</v>
                        </o>
                      </l2>
                      <v n="Id">269L</v>
                      <v n="IdParent">9L</v>
                    </o>
                  </l2>
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">354L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">355L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">356L</v>
                    <v n="IdParent">9L</v>
                  </o>
                </l2>
                <v n="Id">9L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Element type specific properties"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Action definitions"</v>
                </o>
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Common properties"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Time definitions"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Exclude this element from build"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the branch to parallel mode"</v>
                </o>
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Name of the element"</v>
                </o>
                <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                  <v n="Identifier">"Duplication"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the step as the initial step"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is active"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Comment of the element"</v>
                </o>
                <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                  <v n="Identifier">"Monitoring"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Indicates transition monitoring setting."</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is activated"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the maximal active time for the step"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Symbol configuration setting of the element"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the minimal active time for the step"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Qualifier of the action association"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                <o>
                  <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Variable"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"Variable"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Call"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Call"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
                <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                <o>
                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"Unspecified"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"Unspecified"</v>
                    </o>
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Read"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Read"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Write"</v>
                      <v n="Value">3L</v>
                      <v n="Key">"Write"</v>
                    </o>
                    <o>
                      <v n="Identifier">"ReadWrite"</v>
                      <v n="Value">4L</v>
                      <v n="Key">"ReadWrite"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
              </d2>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
            <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
            <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCActionAssociation">{a94bb75d-5fb3-40ad-9d01-41d5b980784d}</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
            <Type n="SFCMacro">{ab40cf8e-1fe8-43b9-aac3-2242e32c7f9e}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
            <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Folder Name="InternalActions" Id="{c20474ff-e84c-47d0-8534-715ec07a3b59}" />
    <Action Name="aContinuousActions" Id="{16e92865-ea65-42fa-be94-fa3158d56caf}" FolderPath="InternalActions\">
      <Implementation>
        <ST><![CDATA[IO(b_EnablePower := b_enablePower);

Get.PrimaryHeatpumpGet REF=PrimaryHeatPump.get;
Get.SecondaryHeatpumpGet REF=SecondaryHeatPump.get;

get.HeatPumpStatus := get.PrimaryHeatpumpGet.HeatPumpState;]]></ST>
      </Implementation>
    </Action>
    <Action Name="aHeatPumpControl" Id="{40cb6c99-f2bd-4463-aec6-f0b22d5ed475}" FolderPath="InternalActions\">
      <Implementation>
        <ST><![CDATA[
//500ms trigger to switch MB bus ownership to next heatpump
CommFreeTimeout(in := NOT CommFreeTimeout.Q);
IF CommFreeTimeout.Q OR (not MBCommBusy) THEN
	CommFreeForID := (CommFreeForID+1) MOD 2;
END_IF

//FB returns MBCommBusy to indicate when status update is done. Could be used for optimized RW speed
//Not used at this moment

PrimaryHeatPump(ACPowerStatus := b_EnablePower, MBFree := (CommFreeForID=0), MBcommBusy => MBcommBusy);
//IF CoolingSystemParams.DoubleHeatpump THEN
//	HeatPumps[2](ACPowerStatus := b_EnablePower, MBFree := (CommFreeForID=1));
//END_IF

]]></ST>
      </Implementation>
    </Action>
    <Action Name="aHeatPumpShutdown" Id="{dfa77b7c-2af9-473e-b37e-15d67f751833}" FolderPath="InternalActions\">
      <Implementation>
        <ST><![CDATA[Get.HeatPumpStatus := eHeatPumpState.OFF;]]></ST>
      </Implementation>
    </Action>
    <Action Name="aInitDone" Id="{e06a6405-dcf9-4ae4-bfbe-c27fe02a41f7}" FolderPath="InternalActions\">
      <Implementation>
        <ST><![CDATA[
get.HeatPumpStatus := eHeatPumpState.Standby;
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aInitHP1" Id="{1d819cdb-f81a-426e-9213-238391d386d3}" FolderPath="InternalActions\">
      <Implementation>
        <ST><![CDATA[
IF Coolingsystemparams.DoubleHeatpump THEN
	SecondaryHeatpump(ACPowerStatus := FALSE, MBFree := FALSE);
END_IF

IF PrimaryHeatpump.get.HeatPumpState <= eHeatpumpstate.Initializing THEN
	PrimaryHeatpump(ACPowerStatus := b_EnablePower, MBFree := TRUE);
ELSIF PrimaryHeatpump.get.HeatPumpState = eHeatpumpstate.Standby THEN
	PrimaryHeatpump(ACPowerStatus := b_EnablePower, MBFree := FALSE);
	SFCTip := TRUE;
END_IF
	


]]></ST>
      </Implementation>
    </Action>
    <Action Name="aInitHP2" Id="{594411e8-2bfb-4a64-a290-320fec4b45d8}" FolderPath="InternalActions\">
      <Implementation>
        <ST><![CDATA[

IF SecondaryHeatpump.get.HeatPumpState = eHeatpumpstate.Initializing THEN
	SecondaryHeatpump(ACPowerStatus := b_EnablePower, MBFree := TRUE);
ELSIF SecondaryHeatpump.get.HeatPumpState = eHeatpumpstate.Standby THEN
	SecondaryHeatpump(ACPowerStatus := b_EnablePower, MBFree := FALSE);
	SFCTip := TRUE;
END_IF
	
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aPowerControl" Id="{7a742825-0880-4e7a-b565-fd6af40350f5}" FolderPath="InternalActions\">
      <Implementation>
        <ST><![CDATA[IO(b_EnablePower := b_enablePower);
]]></ST>
      </Implementation>
    </Action>
    <Method Name="EMStop" Id="{c5d59058-fc75-4523-8e14-2a1384499863}">
      <Declaration><![CDATA[METHOD EMStop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[EMstop := PrimaryHeatpump.emstop() and SecondaryHeatpump.emstop();]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetDiagnostics" Id="{897c308b-8471-40f4-850e-e89d0aac515c}">
      <Declaration><![CDATA[METHOD GetDiagnostics 
VAR_IN_OUT
	AddError		: ARRAY [*] OF FB_AddErrorST;
	a_ActiveEvents	: ARRAY [*] OF ST_ErrorStruct;
	w_Index			: WORD;
END_VAR

VAR_OUTPUT
	b_errorActive	: BOOL;
	b_warningActive	: BOOL;
END_VAR

VAR
	by_errCt	: BYTE;
	by_warnCt	: BYTE;
	w_ID		: WORD;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//check if this call works:
PrimaryHeatpump.GetDiagnostics(AddError := AddError, a_ActiveEvents := a_ActiveEvents, w_Index := w_Index, b_errorActive => b_errorActive, b_warningActive => b_warningActive);

//not in use
//Heatpumps[2].GetDiagnostics(AddError := AddError, a_ActiveEvents := a_ActiveEvents, w_Index := w_Index, b_errorActive => b_errorActive, b_warningActive => b_warningActive);
]]></ST>
      </Implementation>
    </Method>
    <Method Name="Reset" Id="{4a0bb0ee-0ec3-4295-bbf7-b62e6e6a1cef}">
      <Declaration><![CDATA[METHOD Reset : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Reset := PrimaryHeatpump.Reset() and SecondaryHeatpump.Reset();]]></ST>
      </Implementation>
    </Method>
    <Action Name="SFCTipReset" Id="{eb10d883-3ce0-4bca-9d41-17668d540ab5}" FolderPath="InternalActions\">
      <Implementation>
        <ST><![CDATA[SFCTip := FALSE;
]]></ST>
      </Implementation>
    </Action>
    <Method Name="WriteSetpoint" Id="{18c61e5f-7dfc-42d9-af3e-d11734e33e5d}">
      <Declaration><![CDATA[METHOD WriteSetpoint : BOOL
VAR_INPUT
	OperatingMode	:	eHeatpumpMode;
	SetPoint		: 	REAL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[PrimaryHeatpump.WriteSetpoint(OperatingMode := OperatingMode, SetPoint := Setpoint);

//This method will also contain potential master/slave temperature differentials and other differences between heatpumps
//Heatpumps[2].WriteSetpoint(OperatingMode := OperatingMode);
]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"3.4.2.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">false</v>
            <v n="UseDefaults">false</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="FB_HeatPumpSystem.aContinuousActions">
      <LineId Id="2" Count="4" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.aHeatPumpControl">
      <LineId Id="2" Count="14" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.aHeatPumpShutdown">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.aInitDone">
      <LineId Id="2" Count="1" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.aInitHP1">
      <LineId Id="2" Count="13" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.aInitHP2">
      <LineId Id="2" Count="8" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.aPowerControl">
      <LineId Id="2" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.EMStop">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.GetDiagnostics">
      <LineId Id="3" Count="5" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.Reset">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.SFCTipReset">
      <LineId Id="2" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeatPumpSystem.WriteSetpoint">
      <LineId Id="3" Count="3" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>