<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ExternalControl" Id="{8e859215-c51a-4c77-a474-4ba070448a0e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ExternalControl
VAR

END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ExternalControl">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>